on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: static analysis
    steps:
    - name: Run jsPerformoBot
      uses: florianmarkusse/jsPerformoBot@v1.4.26
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}