on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: static analysis
    steps:
    - uses: actions/checkout@v2

    - name: Run jsPerformoBot
      uses: florianmarkusse/jsPerformoBot@v2.0.4
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
