on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Run jsPerformoBot
      uses: florianmarkusse/jsPerformoBot@v1.4.1
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}"