on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: static analysis
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '14.15.1'

    - name: Run jsPerformoBot
      uses: florianmarkusse/jsPerformoBot@v1.4.48
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}